defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

base_path: ""

kramdown:
  input: GFM
  auto_ids: true
highlighter: rouge
